### ISSUE TITLE
SSL error when authenticating?

### ISSUE THREAD

**Issue by qria** [spoqa/geofront#15]
Hi, I got this error when I tried to authenticate with `geofront-cli authenticate`.

I'm using geofront-cli 0.3.3

```bash
(dodo) Qrias-MacBook-Pro:dodo qria$ geofront-cli authenticate
Traceback (most recent call last):
  File "/Users/qria/.venvs/dodo/bin/geofront-cli", line 11, in <module>
    sys.exit(main())
  File "/Users/qria/.venvs/dodo/lib/python2.7/site-packages/geofrontcli/cli.py", line 468, in main
    args.function(args)
  File "/Users/qria/.venvs/dodo/lib/python2.7/site-packages/geofrontcli/cli.py", line 121, in authenticate
    with client.authenticate() as url:
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/qria/.venvs/dodo/lib/python2.7/site-packages/geofrontcli/client.py", line 144, in authenticate
    with self.request('PUT', ('tokens', token_id)) as response:
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/qria/.venvs/dodo/lib/python2.7/site-packages/geofrontcli/client.py", line 76, in request
    response = urlopen(request)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 409, in _open
    '_open', req)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 1181, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 1148, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:507: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>
(dodo) Qrias-MacBook-Pro:dodo qria$ geofront-cli --version
geofront-cli 0.3.3
(dodo) Qrias-MacBook-Pro:dodo qria$ cat ~/Library/Preferences/geofront-cli/server
https://geofront.internal.spoqa.com/
```

**Comment by dahlia** [comment]
@qria Is this still reproduced?

**Comment by qria** [comment]
Yes.

```sh
(dodo) Qrias-MacBook-Pro:dodo qria$ geofront-cli authenticate
Traceback (most recent call last):
  File "/Users/qria/.venvs/dodo/bin/geofront-cli", line 11, in <module>
    sys.exit(main())
  File "/Users/qria/.venvs/dodo/lib/python2.7/site-packages/geofrontcli/cli.py", line 468, in main
    args.function(args)
  File "/Users/qria/.venvs/dodo/lib/python2.7/site-packages/geofrontcli/cli.py", line 121, in authenticate
    with client.authenticate() as url:
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/qria/.venvs/dodo/lib/python2.7/site-packages/geofrontcli/client.py", line 144, in authenticate
    with self.request('PUT', ('tokens', token_id)) as response:
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/qria/.venvs/dodo/lib/python2.7/site-packages/geofrontcli/client.py", line 76, in request
    response = urlopen(request)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 409, in _open
    '_open', req)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 1181, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 1148, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:507: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>
```

with updated geofront client:

```
(dodo) Qrias-MacBook-Pro:dodo qria$ pip install -U geofront-cli
/Users/qria/.venvs/dodo/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/Users/qria/.venvs/dodo/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting geofront-cli
Requirement already up-to-date: six in /Users/qria/.venvs/dodo/lib/python2.7/site-packages (from geofront-cli)
Requirement already up-to-date: enum34 in /Users/qria/.venvs/dodo/lib/python2.7/site-packages (from geofront-cli)
Collecting keyring>=3.7 (from geofront-cli)
  Downloading keyring-10.3.2-py2.py3-none-any.whl
Installing collected packages: keyring, geofront-cli
  Found existing installation: keyring 10.3
    Uninstalling keyring-10.3:
      Successfully uninstalled keyring-10.3
  Found existing installation: geofront-cli 0.3.3
    Uninstalling geofront-cli-0.3.3:
      Successfully uninstalled geofront-cli-0.3.3
Successfully installed geofront-cli-0.3.4 keyring-10.3.2
(dodo) Qrias-MacBook-Pro:dodo qria$ geofront-cli authenticate
Traceback (most recent call last):
  File "/Users/qria/.venvs/dodo/bin/geofront-cli", line 11, in <module>
    sys.exit(main())
  File "/Users/qria/.venvs/dodo/lib/python2.7/site-packages/geofrontcli/cli.py", line 470, in main
    args.function(args)
  File "/Users/qria/.venvs/dodo/lib/python2.7/site-packages/geofrontcli/cli.py", line 121, in authenticate
    with client.authenticate() as url:
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/qria/.venvs/dodo/lib/python2.7/site-packages/geofrontcli/client.py", line 144, in authenticate
    with self.request('PUT', ('tokens', token_id)) as response:
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/qria/.venvs/dodo/lib/python2.7/site-packages/geofrontcli/client.py", line 76, in request
    response = urlopen(request)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 409, in _open
    '_open', req)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 1181, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/Users/qria/.pyenv/versions/2.7/lib/python2.7/urllib2.py", line 1148, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:507: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>
```

**Comment by qria** [comment]
I installed it outside virtualenv with command `pip3 install --user geofront-cli` and it works now.

Sorry for the confusion.
