### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'filename'

### ISSUE THREAD

**Issue by FPurchess** [spoqa/geofront#7]
While evaluating geofront, the following exception occured:

``` python
Traceback (most recent call last):
  File ".virtualenvs/geofront/bin/geofront-server", line 11, in <module>
    sys.exit(main())
  File ".virtualenvs/geofront/lib/python3.4/site-packages/geofront/server.py", line 1042, in main
    not os.environ.get('WERKZEUG_RUN_MAIN'))
  File ".virtualenvs/geofront/lib/python3.4/site-packages/geofront/util.py", line 52, in wrapped
    return function(*args, **kwargs)
  File ".virtualenvs/geofront/lib/python3.4/site-packages/geofront/regen.py", line 64, in regenerate
    key = master_key_store.load()
  File ".virtualenvs/geofront/lib/python3.4/site-packages/geofront/util.py", line 52, in wrapped
    return function(*args, **kwargs)
  File ".virtualenvs/geofront/lib/python3.4/site-packages/geofront/masterkey.py", line 303, in load
    return cls.from_private_key_file(self.path)
  File ".virtualenvs/geofront/lib/python3.4/site-packages/paramiko/pkey.py", line 183, in from_private_key_file
    key = cls(filename=filename, password=password)
TypeError: __init__() got an unexpected keyword argument 'filename'
```

This is how my configuration looks like

``` python
from geofront.backends.github import GitHubOrganization

TEAM = GitHubOrganization(
   client_id='xxxx',
   client_secret='xxxx',
   org_login='YOUR_TEAM'
)

from geofront.backends.github import GitHubKeyStore

KEY_STORE = GitHubKeyStore()

from geofront.backends.cloud import CloudMasterKeyStore
from geofront.masterkey import FileSystemMasterKeyStore
from libcloud.storage.types import Provider
from libcloud.storage.providers import get_driver

MASTER_KEY_STORE = FileSystemMasterKeyStore('an-absolute-path-to-my-master-key')

from geofront.backends.cloud import CloudRemoteSet
from libcloud.compute.types import Provider
from libcloud.compute.providers import get_driver
from geofront.remote import Remote

REMOTE_SET = {
    'web-1': Remote('ubuntu', 'xxx.xxx.xxx.xxx'),
}

from geofront.remote import GroupMetadataPermissionPolicy

PERMISSION_POLICY = GroupMetadataPermissionPolicy('Allowed-Groups')

from werkzeug.contrib.cache import RedisCache

TOKEN_STORE = RedisCache(host='localhost', db=0)
```

installed packages + versions

```
$ pip freeze
Flask==0.10.1
Geofront==0.2.2
Jinja2==2.7.3
MarkupSafe==0.23
Werkzeug==0.10.4
apache-libcloud==0.17.0
backports.ssl-match-hostname==3.4.0.2
ecdsa==0.13
itsdangerous==0.24
paramiko==1.15.2
pycrypto==2.6.1
redis==2.10.3
waitress==0.8.9
```

**Comment by dahlia** [comment]
Could you try this again on the current master?
